"use client";

import { useEffect } from "react";

/** Registers the precache service worker generated by scripts/generate-sw.mjs
 * (only present in production static-export builds -- `next dev` has no
 * out/sw.js, so a 404 there is expected and silently ignored). Once
 * registered, the whole app keeps working offline, including a mobile
 * browser reloading a backgrounded tab with no signal. */
export function RegisterServiceWorker() {
  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;
    const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
    navigator.serviceWorker.register(`${basePath}/sw.js`).catch(() => {
      // No service worker in dev, or registration failed -- the app still
      // works online either way, so this is safe to swallow.
    });
  }, []);

  return null;
}
