// Runs after `next build` (see package.json's build script). A static
// export has no server to generate anything at request time, so this walks
// the finished `out/` directory and writes a service worker with every
// output file baked into its precache list -- once a visitor has loaded the
// page once, the whole app (JS, CSS, fonts, all 42 tile SVGs) is cached and
// keeps working with zero network, including a mobile browser reloading a
// backgrounded tab while offline (e.g. a subway tunnel), which otherwise
// shows a browser-level "no internet" page instead of the app.
import { createHash } from "node:crypto";
import { readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const isGithubPagesBuild = process.env.GITHUB_PAGES === "true";
const basePath = isGithubPagesBuild ? "/mahjongisfun" : "";
const outDir = path.join(process.cwd(), "out");

function walk(dir, base = "") {
  const files = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    const rel = `${base}/${entry.name}`;
    if (entry.isDirectory()) {
      files.push(...walk(abs, rel));
    } else {
      files.push(rel);
    }
  }
  return files;
}

const relativePaths = walk(outDir).sort();

const hash = createHash("sha256");
for (const rel of relativePaths) {
  hash.update(rel);
  hash.update(String(statSync(path.join(outDir, rel)).size));
}
const version = hash.digest("hex").slice(0, 12);

const precacheUrls = relativePaths.map((rel) => JSON.stringify(`${basePath}${rel}`));

const swSource = `// Auto-generated by scripts/generate-sw.mjs -- do not edit by hand.
const CACHE_NAME = "mahjong-precache-${version}";
const BASE = ${JSON.stringify(basePath)};
const APP_SHELL = \`\${BASE}/index.html\`;
const PRECACHE_URLS = [
${precacheUrls.map((u) => `  ${u},`).join("\n")}
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) =>
        Promise.all(PRECACHE_URLS.map((url) => cache.add(url).catch(() => {})))
      )
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  // Page navigations: prefer the network (so a visitor back online gets the
  // latest deploy), but fall back to the cached app shell when offline --
  // this is what keeps a reloaded/backgrounded tab from dying underground.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request).catch(() => caches.match(APP_SHELL).then((res) => res || caches.match(request)))
    );
    return;
  }

  // Everything else (hashed JS/CSS, fonts, tile art): cache-first, since
  // build output filenames are content-hashed and immutable once built.
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => cached);
    })
  );
});
`;

writeFileSync(path.join(outDir, "sw.js"), swSource);
console.log(`Generated out/sw.js (cache ${version}, ${relativePaths.length} precached files)`);
